### ISSUE TITLE
Create tutorial to demonstrate a Tekton CI&CD pipeline for App Connect Enterprise (ACE) deployment using Helm Chart

### ISSUE THREAD

**Issue by hollisc** [ibm-cloud-architecture/gse-devops#18]
**Overview:** Using Tekton, create a CI&CD pipeline to automate the deployment of an ACE server instance on OpenShift. 

**Pre-req:** 
- Provision an OpenShift 43x cluster
- Install the Cloud Pak for Integration
- Provision an instance of the ACE Dashboard

**Activities:** 
- [ ] Set up a sample Inventory microservice and expose an API. 
- [x] Set up an ACE Toolkit project using a REST based subflow to reference the Inventory API.
- [x] Create Tekton CI Pipeline and Task(s) to do the following: Compile bar and store it in a repository, create an image of the ACE server with the bar file included and push it to a registry, deploy the ACE Helm Chart using the built image.
- [x] Document instructions in a README
- [ ] Playback
- [ ] Recording
