### ISSUE TITLE
Create tutorial to demonstrate how to version control and manage Tekton Pipelines using Kabanero

### ISSUE THREAD

**Issue by hollisc** [ibm-cloud-architecture/gse-devops#19]
**Overview:** Using Tekton, create a CI&CD pipeline to automate the management and deployment of Tekton Pipeline(s) and Task(s) on OpenShift. 

**Pre-req:** 
- Provision an OpenShift 43x cluster
- Install Cloud Pak for Application or Kabanero 

**Activities:** 
- [x] Set up a Git repository and load the repo with the default Kabanero Pipelines and Tasks
- [x] Create a new Tekton Pipeline(s) and/or Task(s).
- [x] Create Tekton CI Pipeline and Task(s) to do the following: Generate a tar containing Tekton Pipeline and Task yamls and store the tar file in a repository, update Kabanero instance to reference the new tar.
- [x] Document instructions in a README
- [ ] Define a new Stack to include additional stages in the pipeline. Tracked via  https://github.com/ibm-cloud-architecture/devops-demo-kabanero-pipelines/issues/31.
- [ ] Playback to team
- [ ] Recording
