### ISSUE TITLE
Create tutorial to demonstrate a CI (Tekton) & CD (MCM) pipeline for application deployment

### ISSUE THREAD

**Issue by hollisc** [ibm-cloud-architecture/gse-devops#20]
**Overview:** Using a Storefront sample application, create a CI (Tekton) and CD (MCM) pipeline to automate the deployment of the application in a GitOps approach on OpenShift.

**Pre-req:** 
- Provision two OpenShift 43x clusters
- Install Cloud Pak for Multicloud Management on one cluster
- Install Cloud Pak for Application on the second cluster.

**Activities:** 
- [x] Deploy Storefront microservices and database backend systems to cluster with Cloud Pak for Application
- [x] Configure git repository to represent DEV environment
- [x] Create Tekton CI Pipeline and Task(s) to do the following: build, test, create an image and push it to a registry, update Kubernetes yaml in the DEV github repo 
- [x] Deploy MCM Application Model resources (Channels, PlacementRule, Subscriptions) to cluster with MCM to configure CD pipeline using gitops approach
- [ ] Document instructions in a README
