### ISSUE TITLE
Create tutorial to demonstrate a CI (Tekton) and CD (CP4MCM) pipeline for Operator based App Connect Enterprise (ACE) deployments

### ISSUE THREAD

**Issue by hollisc** [ibm-cloud-architecture/gse-devops#26]
**Overview:** Demonstrate a CI (Tekton) and CD (CP4MCM) pipeline to build and deploy an Operator based App Connect Enterprise (ACE) deployment

**Environments:** 
- OpenShift 4.x cluster + CloudPak for Integration 2020.2.1
- OpenShift 4.x cluster + CloudPak for MultiCloud Management 1.3

**Activities:** 
- [ ] Deploy a sample microservice with a REST API call which returns a json containing a list of items 
- [ ] Set up an ACE Toolkit project using a REST based subflow to reference the sample microservice API.
- [ ]  Configure CP4MCM instance with Channel, PlacementRule, Subscription resources for a gitops flow
- [ ] Create Tekton CI Pipeline and Task(s) to do the following: Clone git repo, Compile bar and upload it to Artifactory, create a custom image of the ACE server with the bar file included and push it to a registry, deploy an IntegrationServer CRD instance using the built image, post a Slack notification, execute smoke test to validate the ACE server instance is running, promote the ACE instance to the next environment using gitops, post a Slack notification once the deployment is complete
- [ ] Document instructions in a README
- [ ] Create a recording
